[project]
name = "quantumlearning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "qiskit-ibm-runtime>=0.42.0",
    "qiskit[visualization]>=2.2.1",
]
